language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install -r dev-requirements.txt
services:
  - postgresql
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS seamless_karma_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE seamless_karma_test;' -U postgres; fi"
# handle multiple databases in build matrix
env:
  - DB=sqlite
  - DB=postgres
script:
  - coverage run --source seamless_karma -m py.test . --db $DB
  - coverage report --show-missing
after_success:
  - coveralls
