language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install: "pip install -r dev-requirements.txt --use-mirrors"
# command to run tests
script: python runtests.py --db $DB
# handle multiple databases in build matrix
env:
  - DB=sqlite
  - DB=postgres
services:
  - postgresql
before_script:
  - psql -c 'create database seamless_karma_test;' -U postgres
  - python manage.py -c test db create
