language: python
python:
  - "2.7"
  - "3.3"
install: "pip install -r dev-requirements.txt --use-mirrors"
services:
  - postgresql
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS seamless_karma_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE seamless_karma_test;' -U postgres; fi"
  - python manage.py -c test db create
# handle multiple databases in build matrix
env:
  - DB=sqlite
  - DB=postgres
script: python runtests.py --db $DB
